### ISSUE TITLE
Add new blog post #2

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-anmmar#8]
Attached.

due:
11-25-15   10a

[The 3 Pillars of Personal Islamic Finance set the building blocks every Muslim should solidly set in order to be successful in their every day money matters.docx](https://github.com/EditLLC/client-anmmar/files/43195/The.3.Pillars.of.Personal.Islamic.Finance.set.the.building.blocks.every.Muslim.should.solidly.set.in.order.to.be.successful.in.their.every.day.money.matters.docx)

**Comment by rampage1213** [comment]
This is posted just fixing up the page its displayed on and designing a Blog page

**Comment by rodneystrong** [comment]
This actually doesn't display well as a blog page. Please review some blogs you follow and post the links here as comments. Then let's have a discussion on what differentiates them from what you created.

due:
12-2-15   3p

**Comment by rampage1213** [comment]
Sorry I missed this due date my fault wont let it happen again. With that being said I see what your saying how my blog page is just white with text over it. 

Some blogs I have read from over time: 
https://reactjsnews.com/
http://hackaday.com/blog/
https://css-tricks.com/

I can see that these blogs have a unique design they are not just white with text even thought reactjsnews is a simple design it has a animation when you first load the site. Hackaday's Blog has first a picture then a title, a paragraph or two then a read more button. Css-tricks design is simple to but is similar to all the blogs where it has a title, paragraph or 2 then a read more button so that the user doesn't get lost in text. With my design a user would just get lost in text instead of reading the title and picking witch topic they want to read on.

**Comment by rampage1213** [comment]
Done!
