### ISSUE TITLE
Fix look of the blog page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-anmmar#9]
Go to this page: http://anmmar.editllc.com/blog-2/

Work with @rampage1213 and enhance this page in terms of usability, utility, and design. 

One site the client really likes is http://christianpf.com/

There are a few items that are missing like titles for each blog post, the actual post date for each post, etc. Look for these items and pull me and @rampage1213 for a discussion on the importance of these items. 

due:
12-15-15   4p

**Comment by jperez4509** [comment]
@rodneystrong :  @rampage1213 and I worked on some of this today. We fixed some of the basic design but he was going to work on linking the articles to the titles. Tomorrow I will work with him again on completing the side bar.

**Comment by rampage1213** [comment]
what I need to fix on the site is fix up the home page and on there fix the bio section so that there is no blog area also, fix the email area on the home page it is coded wrong. On the start here page, there is a books section I need to make that more realistic by adding title and price area. Lastly when you view a blog post the title is not showing "the_title() needs to be added to single.php"
